name: Deploy to cPanel

on:
    push:
        branches:
            - main # Runs only when code is pushed or merged to main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.ID_RSA_GITHUB_CPANEL_AIG_BE }}" > ~/.ssh/id_rsa_github_cpanel_aig_be
                  chmod 600 ~/.ssh/id_rsa_github_cpanel_aig_be
                  ssh-keyscan -p ${{ secrets.CPANEL_PORT }} -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to cPanel
              run: |
                  ssh -p ${{ secrets.CPANEL_PORT }} -i ~/.ssh/id_rsa_github_cpanel_aig_be ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} << 'EOF'
                  set -e  # Stop script if any command fails

                  # Navigate to deployment folder
                  cd /home2/${{ secrets.CPANEL_USERNAME }}/newsaibe

                  # Ensure the directory is a git repository
                  if [ ! -d ".git" ]; then
                    git init
                    git remote add origin https://github.com/kkatusic/news_flow.git
                  fi

                  # Pull the latest code
                  git fetch origin main
                  git reset --hard origin/main

                  # Install dependencies
                  if ! command -v pnpm &> /dev/null; then
                    npm install -g pnpm
                  fi
                  pnpm install --prod

                  # Restart application if PM2 is installed
                  if command -v pm2 &> /dev/null; then
                    pm2 restart all
                  else
                    echo "PM2 not found, skipping restart"
                  fi
                  EOF
